### ISSUE TITLE
ValueError: Invalid arguments passed to DefaultPredictiveImputer __init__ method

### ISSUE THREAD

**Issue by nick-youngblut** [kearnz/autoimpute#70]
From the 2nd tutorial:

```
import numpy as np
import pandas as pd
from autoimpute.imputations import SingleImputer

toy_df = pd.DataFrame({
    "age": np.random.choice(np.arange(20,80), 50),
    "gender": np.random.choice(["Male","Female"], 50),
    "employment": np.random.choice(["Unemployed","Employed", "Part Time", "Self-Employed"], 50),
    "salary": np.random.choice(np.arange(50_000, 1_000_000), 50),
    "weight": np.random.choice(np.arange(100, 300, 0.1), 50),
})

si = SingleImputer()
si.fit(toy_df)
```

Produces the following error:

```
Traceback (most recent call last):
  File "/ebio/abt3_projects/impute_proj/envs/impute/lib/python3.8/site-packages/autoimpute/imputations/dataframe/single_imputer.py", line 168, in fit
    imputer = imp()
  File "/ebio/abt3_projects/impute_proj/envs/impute/lib/python3.8/site-packages/autoimpute/imputations/series/default.py", line 385, in __init__
    DefaultBaseImputer.__init__(
  File "/ebio/abt3_projects/impute_proj/envs/impute/lib/python3.8/site-packages/autoimpute/imputations/series/default.py", line 53, in __init__
    self.num_imputer = num_imputer
  File "/ebio/abt3_projects/impute_proj/envs/impute/lib/python3.8/site-packages/autoimpute/imputations/series/default.py", line 119, in num_imputer
    self._num_imputer = imp()
  File "/ebio/abt3_projects/impute_proj/envs/impute/lib/python3.8/site-packages/autoimpute/imputations/series/pmm.py", line 95, in __init__
    self.lm = LinearRegression(
TypeError: __init__() takes 1 positional argument but 5 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./bin/scripts/impute_autoimpute.py", line 91, in <module>
    main(args)
  File "./bin/scripts/impute_autoimpute.py", line 73, in main
    si.fit(toy_df)
  File "/ebio/abt3_projects/impute_proj/envs/impute/lib/python3.8/site-packages/autoimpute/utils/checks.py", line 61, in wrapper
    return func(d, *args, **kwargs)
  File "/ebio/abt3_projects/impute_proj/envs/impute/lib/python3.8/site-packages/autoimpute/utils/checks.py", line 126, in wrapper
    return func(d, *args, **kwargs)
  File "/ebio/abt3_projects/impute_proj/envs/impute/lib/python3.8/site-packages/autoimpute/utils/checks.py", line 173, in wrapper
    return func(d, *args, **kwargs)
  File "/ebio/abt3_projects/impute_proj/envs/impute/lib/python3.8/site-packages/autoimpute/imputations/dataframe/single_imputer.py", line 174, in fit
    raise ValueError(err) from te
ValueError: Invalid arguments passed to DefaultPredictiveImputer __init__ method.
```

## conda env

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
absl-py                   1.0.0                    pypi_0    pypi
aiohttp                   3.8.1            py38h497a2fe_0    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38h497a2fe_1    conda-forge
arviz                     0.11.4                   pypi_0    pypi
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
autoimpute                0.12.2                   pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                 hf3e587d_3    conda-forge
bioconductor-biobase      2.54.0            r41hd029910_0    bioconda
bioconductor-biocgenerics 0.40.0            r41hdfd78af_0    bioconda
bioconductor-biomformat   1.22.0            r41hdfd78af_0    bioconda
bioconductor-biostrings   2.62.0            r41hd029910_0    bioconda
bioconductor-genomeinfodb 1.30.0            r41hdfd78af_0    bioconda
bioconductor-genomeinfodbdata 1.2.7             r41hdfd78af_1    bioconda
bioconductor-iranges      2.28.0            r41hd029910_0    bioconda
bioconductor-multtest     2.50.0            r41hd029910_0    bioconda
bioconductor-phyloseq     1.38.0            r41hdfd78af_0    bioconda
bioconductor-rhdf5        2.38.0            r41hfe70e90_1    bioconda
bioconductor-rhdf5filters 1.6.0             r41h399db7b_0    bioconda
bioconductor-rhdf5lib     1.16.0            r41hd029910_0    bioconda
bioconductor-s4vectors    0.32.0            r41hd029910_0    bioconda
bioconductor-xvector      0.34.0            r41hd029910_0    bioconda
bioconductor-zlibbioc     1.40.0            r41hd029910_0    bioconda
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blinker                   1.4                        py_1    conda-forge
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1003    conda-forge
bwidget                   1.9.14               ha770c72_1    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.26           h06a4308_2
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
certifi                   2021.10.8                pypi_0    pypi
cffi                      1.15.0           py38h3931269_0    conda-forge
cftime                    1.5.1.1                  pypi_0    pypi
charset-normalizer        2.0.9              pyhd8ed1ab_0    conda-forge
click                     8.0.3            py38h578d9bd_1    conda-forge
cryptography              36.0.1           py38h3e25421_0    conda-forge
cudatoolkit               11.5.0               h36ae40a_9    conda-forge
cudnn                     8.2.1.32             h86fa8c9_0    conda-forge
curl                      7.80.0               h2574ce0_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dbus                      1.13.18              hb2f20db_0
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.4                    pypi_0    pypi
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.4.2                h9c3ff4c_0    conda-forge
fastprogress              1.0.0                    pypi_0    pypi
filelock                  3.4.2                    pypi_0    pypi
flatbuffers               2.0                      pypi_0    pypi
flit-core                 3.6.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.28.5           py38h497a2fe_0    conda-forge
freetype                  2.11.0               h70c0345_0
fribidi                   1.0.10               h516909a_0    conda-forge
frozenlist                1.2.0            py38h497a2fe_1    conda-forge
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
gcc_impl_linux-64         9.4.0               h03d3576_11    conda-forge
gcc_linux-64              9.4.0                h391b98a_3    conda-forge
gettext                   0.21.0               hf68c758_0
gfortran_impl_linux-64    9.4.0               h0003116_11    conda-forge
gfortran_linux-64         9.4.0                hf0ab688_3    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.70.2               h780b84a_1    conda-forge
glib-tools                2.70.2               h780b84a_1    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
google-auth               2.3.3              pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
graphite2                 1.3.14               h23475e2_0
grpc-cpp                  1.39.1               h850795e_1    conda-forge
grpcio                    1.43.0                   pypi_0    pypi
gsl                       2.7                  he838d99_0    conda-forge
gst-plugins-base          1.18.5               hf529b03_2    conda-forge
gstreamer                 1.18.5               h9f60fe5_2    conda-forge
gxx_impl_linux-64         9.4.0               h03d3576_11    conda-forge
gxx_linux-64              9.4.0                h0316aca_3    conda-forge
h5py                      3.6.0                    pypi_0    pypi
harfbuzz                  3.1.1                h83ec7ef_0    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd3eb1b0_0
importlib-metadata        4.10.0           py38h578d9bd_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
ipykernel                 5.5.5            py38hd0cf306_0    conda-forge
ipython                   7.30.1           py38h578d9bd_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1           py38h578d9bd_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
jsonschema                4.3.2              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py38h578d9bd_7    conda-forge
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py38h578d9bd_1    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
keras                     2.7.0                    pypi_0    pypi
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
kiwisolver                1.3.2            py38h1fd1430_1    conda-forge
krb5                      1.19.2               hcc1bbae_3    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           12_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0           12_linux64_openblas    conda-forge
libclang                  12.0.0                   pypi_0    pypi
libcurl                   7.80.0               h2574ce0_0    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libedit                   3.1.20210714         h7f8727e_0
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     9.4.0               hd854feb_11    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libglib                   2.70.2               h174f98d_1    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           12_linux64_openblas    conda-forge
libllvm11                 11.1.0               hf817b99_2    conda-forge
libnghttp2                1.46.0               hce63b2e_0
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.5                h27cfd23_1
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libpq                     13.5                 hd57d9b9_1    conda-forge
libprotobuf               3.16.0               h780b84a_0    conda-forge
libsanitizer              9.4.0               h79bfe98_11    conda-forge
libsodium                 1.0.18               h516909a_1    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-devel_linux-64  9.4.0               hd854feb_11    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libvorbis                 1.3.7                he1b5a44_0    conda-forge
libwebp-base              1.2.1                h7f98852_0    conda-forge
libxcb                    1.14                 h7b6447c_0
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
markdown                  3.3.6              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py38h497a2fe_1    conda-forge
matplotlib                3.5.1            py38h578d9bd_0    conda-forge
matplotlib-base           3.5.1            py38hf4fb855_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
midaspy                   1.2.1                    pypi_0    pypi
missingno                 0.5.0                    pypi_0    pypi
mistune                   0.8.4           py38h497a2fe_1005    conda-forge
multidict                 5.2.0            py38h497a2fe_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.27               ha770c72_3    conda-forge
mysql-libs                8.0.27               hfa10184_3    conda-forge
nb_conda_kernels          2.3.1            py38h578d9bd_1    conda-forge
nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge
nbconvert                 6.3.0            py38h578d9bd_1    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nccl                      2.11.4.1             hdc17891_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.8                    pypi_0    pypi
notebook                  6.4.6              pyha770c72_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.73                 hb5efdd6_0    conda-forge
numpy                     1.22.0                   pypi_0    pypi
oauthlib                  3.1.1              pyhd8ed1ab_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.5            py38h43a58ef_0    conda-forge
pandoc                    2.16.2               h7f98852_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
pango                     1.48.10              h54213e6_2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2                    pypi_0    pypi
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.37                h032f7d1_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py38h8e6f84c_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
prompt_toolkit            3.0.24               hd8ed1ab_0    conda-forge
protobuf                  3.19.1                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.1             pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
pymc3                     3.11.4                   pypi_0    pypi
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py38ha8c2ead_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.18.0           py38h497a2fe_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_4    conda-forge
python                    3.8.12          hb7a2778_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-flatbuffers        1.12               pyhd8ed1ab_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyzmq                     22.3.0           py38h2035c66_1    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
qtconsole                 5.2.2              pyhd8ed1ab_1    conda-forge
qtconsole-base            5.2.2              pyhd8ed1ab_1    conda-forge
qtpy                      2.0.0              pyhd8ed1ab_0    conda-forge
r-ade4                    1.7_18            r41he454529_0    conda-forge
r-ape                     5.6               r41h306847c_0    conda-forge
r-argparse                2.1.3             r41hc72bb7e_0    conda-forge
r-assertthat              0.2.1             r41hc72bb7e_2    conda-forge
r-backports               1.4.1             r41hcfec24a_0    conda-forge
r-base                    4.1.1                hb93adac_1    conda-forge
r-base64enc               0.1_3           r41hcfec24a_1004    conda-forge
r-bit                     4.0.4             r41hcfec24a_0    conda-forge
r-bit64                   4.0.5             r41hcfec24a_0    conda-forge
r-bitops                  1.0_7             r41hcfec24a_0    conda-forge
r-brio                    1.1.3             r41hcfec24a_0    conda-forge
r-callr                   3.7.0             r41hc72bb7e_0    conda-forge
r-cli                     3.1.0             r41h03ef668_0    conda-forge
r-cluster                 2.1.2             r41h859d828_0    conda-forge
r-clustermq               0.8.95.2          r41h42bf92c_0    conda-forge
r-codetools               0.2_18            r41hc72bb7e_0    conda-forge
r-colorspace              2.0_2             r41hcfec24a_0    conda-forge
r-crayon                  1.4.2             r41hc72bb7e_0    conda-forge
r-data.table              1.14.2            r41hcfec24a_0    conda-forge
r-desc                    1.4.0             r41hc72bb7e_0    conda-forge
r-diffobj                 0.3.5             r41hcfec24a_0    conda-forge
r-digest                  0.6.29            r41h03ef668_0    conda-forge
r-dplyr                   1.0.7             r41h03ef668_0    conda-forge
r-ellipsis                0.3.2             r41hcfec24a_0    conda-forge
r-evaluate                0.14              r41hc72bb7e_2    conda-forge
r-fansi                   0.4.2             r41hcfec24a_0    conda-forge
r-farver                  2.1.0             r41h03ef668_0    conda-forge
r-fastmap                 1.1.0             r41h03ef668_0    conda-forge
r-findpython              1.0.7             r41hc72bb7e_0    conda-forge
r-foreach                 1.5.1             r41hc72bb7e_0    conda-forge
r-generics                0.1.1             r41hc72bb7e_0    conda-forge
r-ggplot2                 3.3.5             r41hc72bb7e_0    conda-forge
r-glmnet                  4.1_2             r41h859d828_0    conda-forge
r-glue                    1.6.0             r41hcfec24a_0    conda-forge
r-gtable                  0.3.0             r41hc72bb7e_3    conda-forge
r-here                    1.0.1             r41hc72bb7e_0    conda-forge
r-hms                     1.1.1             r41hc72bb7e_0    conda-forge
r-htmltools               0.5.2             r41h03ef668_0    conda-forge
r-igraph                  1.2.10            r41he0372cf_0    conda-forge
r-irdisplay               1.0               r41hd8ed1ab_0    conda-forge
r-irkernel                1.2               r41hc72bb7e_0    conda-forge
r-isoband                 0.2.5             r41h03ef668_0    conda-forge
r-iterators               1.0.13            r41hc72bb7e_0    conda-forge
r-jsonlite                1.7.2             r41hcfec24a_0    conda-forge
r-labeling                0.4.2             r41hc72bb7e_1    conda-forge
r-lattice                 0.20_45           r41hcfec24a_0    conda-forge
r-lifecycle               1.0.1             r41hc72bb7e_0    conda-forge
r-magrittr                2.0.1             r41hcfec24a_1    conda-forge
r-mass                    7.3_54            r41hcfec24a_0    conda-forge
r-matrix                  1.4_0             r41he454529_0    conda-forge
r-mgcv                    1.8_38            r41he454529_0    conda-forge
r-mltools                 0.3.5             r41hc72bb7e_1    conda-forge
r-munsell                 0.5.0           r41hc72bb7e_1004    conda-forge
r-nada                    1.6_1.1           r41hc72bb7e_1    conda-forge
r-narray                  0.4.1.1           r41hc72bb7e_0    conda-forge
r-nlme                    3.1_153           r41h859d828_0    conda-forge
r-pbdzmq                  0.3_6             r41h42bf92c_0    conda-forge
r-permute                 0.9_5             r41h785f33e_3    conda-forge
r-pillar                  1.6.4             r41hc72bb7e_0    conda-forge
r-pixmap                  0.4_12            r41hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r41hc72bb7e_1    conda-forge
r-pkgload                 1.2.4             r41h03ef668_0    conda-forge
r-plyr                    1.8.6             r41h03ef668_1    conda-forge
r-png                     0.1_7           r41hcfec24a_1004    conda-forge
r-praise                  1.0.0           r41hc72bb7e_1005    conda-forge
r-prettyunits             1.1.1             r41hc72bb7e_1    conda-forge
r-processx                3.5.2             r41hcfec24a_0    conda-forge
r-progress                1.2.2             r41hc72bb7e_2    conda-forge
r-ps                      1.6.0             r41hcfec24a_0    conda-forge
r-purrr                   0.3.4             r41hcfec24a_1    conda-forge
r-qs                      0.25.2            r41h2d4f71f_0    conda-forge
r-r.methodss3             1.8.1             r41hc72bb7e_0    conda-forge
r-r.oo                    1.24.0            r41hc72bb7e_0    conda-forge
r-r.utils                 2.11.0            r41hc72bb7e_0    conda-forge
r-r6                      2.5.1             r41hc72bb7e_0    conda-forge
r-rapiserialize           0.1.0             r41h03ef668_1    conda-forge
r-rappdirs                0.3.3             r41hcfec24a_0    conda-forge
r-rcolorbrewer            1.1_2           r41h785f33e_1003    conda-forge
r-rcpp                    1.0.7             r41h03ef668_0    conda-forge
r-rcppparallel            5.1.4             r41h03ef668_0    conda-forge
r-rcurl                   1.98_1.5          r41hcfec24a_0    conda-forge
r-rematch2                2.1.2             r41hc72bb7e_1    conda-forge
r-renv                    0.14.0            r41hc72bb7e_0    conda-forge
r-repr                    1.1.3             r41h785f33e_0    conda-forge
r-reshape2                1.4.4             r41h03ef668_1    conda-forge
r-reticulate              1.22              r41h03ef668_0    conda-forge
r-rhpcblasctl             0.21_247.1        r41hcfec24a_0    conda-forge
r-rlang                   0.4.12            r41hcfec24a_0    conda-forge
r-rprojroot               2.0.2             r41hc72bb7e_0    conda-forge
r-rstudioapi              0.13              r41hc72bb7e_0    conda-forge
r-scales                  1.1.1             r41hc72bb7e_0    conda-forge
r-shape                   1.4.6             r41ha770c72_0    conda-forge
r-sp                      1.4_6             r41hcfec24a_0    conda-forge
r-stringfish              0.15.5            r41h03ef668_0    conda-forge
r-stringi                 1.7.6             r41hcabe038_0    conda-forge
r-stringr                 1.4.0             r41hc72bb7e_2    conda-forge
r-survival                3.2_13            r41hcfec24a_0    conda-forge
r-testthat                3.1.1             r41h03ef668_0    conda-forge
r-tibble                  3.1.6             r41hcfec24a_0    conda-forge
r-tidyr                   1.1.4             r41h03ef668_0    conda-forge
r-tidyselect              1.1.1             r41hc72bb7e_0    conda-forge
r-tidytable               0.6.6             r41hc72bb7e_0    conda-forge
r-truncnorm               1.0_8           r41hcfec24a_1002    conda-forge
r-utf8                    1.2.2             r41hcfec24a_0    conda-forge
r-uuid                    1.0_3             r41hcfec24a_0    conda-forge
r-vctrs                   0.3.8             r41hcfec24a_1    conda-forge
r-vegan                   2.5_7             r41h52d45c5_0    conda-forge
r-viridislite             0.4.0             r41hc72bb7e_0    conda-forge
r-waldo                   0.3.1             r41hc72bb7e_0    conda-forge
r-withr                   2.4.3             r41hc72bb7e_0    conda-forge
r-zcompositions           1.3.4             r41hc72bb7e_1    conda-forge
re2                       2021.09.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
rsa                       4.8                pyhd8ed1ab_0    conda-forge
scikit-learn              1.0.2            py38h1561384_0    conda-forge
scipy                     1.7.3            py38h56a6a73_0    conda-forge
seaborn                   0.11.2                   pypi_0    pypi
sed                       4.8                  he412f7d_0    conda-forge
semver                    2.13.0                   pypi_0    pypi
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                60.2.0           py38h578d9bd_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
statsmodels               0.13.1                   pypi_0    pypi
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tensorboard               2.7.0              pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0              pyh44b312d_0    conda-forge
tensorflow                2.7.0                    pypi_0    pypi
tensorflow-addons         0.15.0                   pypi_0    pypi
tensorflow-base           2.6.0           cuda112py38heae9c4c_2    conda-forge
tensorflow-estimator      2.7.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.23.1                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.12.1           py38h578d9bd_1    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
theano-pymc               1.1.2                    pypi_0    pypi
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tktable                   2.10                 hb7b940f_3    conda-forge
tornado                   6.1              py38h497a2fe_2    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typeguard                 2.13.3                   pypi_0    pypi
typing-extensions         3.10.0.2                 pypi_0    pypi
typing_extensions         3.7.4.3                    py_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
unicodedata2              14.0.0           py38h497a2fe_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.0.2              pyhd3eb1b0_0
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.5.2            py38h578d9bd_1    conda-forge
wrapt                     1.13.3                   pypi_0    pypi
xarray                    0.20.2                   pypi_0    pypi
xgboost                   1.5.1                    pypi_0    pypi
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yarl                      1.7.2            py38h497a2fe_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.1                ha95c52a_0    conda-forge
```

**Comment by kearnz** [comment]
@nick-youngblut apologies for the delay here. a couple of these issues coming up w/ newer versions of python. looking into root cause in the next week and will get back to you!

**Comment by kearnz** [comment]
pushed a change that should fix this. If you're still having issues please open another issue and will continue to investigate!
